name: docker

on: [push, workflow_dispatch]

jobs:
   buildx:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform  linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
            --output "type=image,push=true"
            -f Dockerfile -t ghcr.io/dumbdogdiner/taco:sha-$GITHUB_SHA .
      - name: Tag and push build as latest (master branch only)
        run: |
          docker tag ghcr.io/dumbdogdiner/taco:sha-$GITHUB_SHA ghcr.io/dumbdogdiner/taco:latest
          docker push ghcr.io/dumbdogdiner/taco:latest
        if: github.ref == 'refs/heads/master'